version: "3.7"

services:

  webserver:
    image: fjakkarin/beyla-nginx:latest
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    depends_on:
      - app

  app:
    image: fjakkarin/beyla-app:latest
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    volumes:
      - ./storage:/var/www/app/storage
    depends_on:
      - database
      - cache

  database:
    image: postgres:12-alpine
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./.build/data/pgdata:/var/lib/postgresql/data

  cache:
    image: redis:alpine
    command: redis-server --appendonly yes --requirepass "$CACHE_PASSWORD}"
    volumes:
      - ./.build/data/redis:/data
    ports:
      - "6379:6379"
